using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MixMedia.MCP.LexOffice.Models;

/// <summary>
/// Represents a Lexoffice credit note.
/// </summary>
public class CreditNote
{
    /// <summary>Unique id of the credit note generated by lexoffice.</summary>
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    /// <summary>Unique id of the organization the credit note belongs to.</summary>
    [JsonPropertyName("organizationId")]
    public Guid OrganizationId { get; set; }

    /// <summary>Version (revision) number for optimistic locking.</summary>
    [JsonPropertyName("version")]
    public int Version { get; set; }

    /// <summary>Credit note number as given by the user or generated by lexoffice.</summary>
    [JsonPropertyName("creditNoteNumber")]
    public string? CreditNoteNumber { get; set; }

    /// <summary>Voucher date of the credit note.</summary>
    [JsonPropertyName("voucherDate")]
    public DateTimeOffset VoucherDate { get; set; }

    /// <summary>Address of the credit note recipient.</summary>
    [JsonPropertyName("address")]
    public InvoiceAddress Address { get; set; } = new();

    /// <summary>Line items of the credit note.</summary>
    [JsonPropertyName("lineItems")]
    public List<InvoiceLineItem> LineItems { get; set; } = new();

    /// <summary>Total price of the credit note.</summary>
    [JsonPropertyName("totalPrice")]
    public InvoiceTotalPrice TotalPrice { get; set; } = new();

    /// <summary>Tax conditions of the credit note.</summary>
    [JsonPropertyName("taxConditions")]
    public InvoiceTaxConditions TaxConditions { get; set; } = new();

    /// <summary>Payment conditions of the credit note.</summary>
    [JsonPropertyName("paymentConditions")]
    public InvoicePaymentConditions PaymentConditions { get; set; } = new();

    /// <summary>Shipping conditions of the credit note.</summary>
    [JsonPropertyName("shippingConditions")]
    public InvoiceShippingConditions ShippingConditions { get; set; } = new();

    /// <summary>Title of the credit note.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }

    /// <summary>Introduction text of the credit note.</summary>
    [JsonPropertyName("introduction")]
    public string? Introduction { get; set; }

    /// <summary>Remark for the credit note.</summary>
    [JsonPropertyName("remark")]
    public string? Remark { get; set; }

    /// <summary>Archived flag of the credit note.</summary>
    [JsonPropertyName("archived")]
    public bool Archived { get; set; }

    /// <summary>XRechnung details (optional).</summary>
    [JsonPropertyName("xRechnung")]
    public object? XRechnung { get; set; } // Replace with a proper model if needed
}
